typography_spectrum: 0.2408273934852332
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9032546991948038
  lightness: 0.5559012815356255
  saturation: 0.9982874367851764
  rhythmicContrast: 0.06482686940580606
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.08382427087053657
analytics:
  google: null
  facebook: null
  twitter: null
name: salesjourney
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Sales Journey
purpose: []
